development:
  adapter: async

test:
  adapter: async

production:
  adapter: async
  # adapter: redis
  # port: 6379
  # url: redis://redis.pray-for-our-world.herokuapp.com:6379
  # url: redis://127.0.0.1:6379
